import { defineConfig } from "vite-plus";

export default defineConfig({
  create: {
    templates: [
      {
        name: "package",
        description: "New workspace package: packages/* (runtime-neutral) or adapters/*",
        template: "./tooling/create-package",
      },
    ],
  },

  lint: {
    plugins: ["unicorn", "typescript", "oxc", "node", "import"],
    env: { builtin: true },
    categories: { correctness: "error" },
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: [
      "**/dist/**",
      "research/**",
      "plan/**",
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".windsurf/**",
      "tools/oxlint/anti-slop/**",
    ],
    jsPlugins: [{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" }],
    rules: {
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": "error",
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",

      "no-deprecated": "warn",
      "typescript/no-misused-spread": "off",

      "constructor-super": "warn",
      "for-direction": "warn",
      "no-async-promise-executor": "warn",
      "no-caller": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "warn",
      "no-constant-binary-expression": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-delete-var": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-empty-static-block": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-self-assign": "warn",
      "no-setter-return": "warn",
      "no-console": "warn",
      "node/no-process-env": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/no-non-null-assertion": "error",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-this-before-super": "warn",
      "no-unassigned-vars": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "no-unsafe-optional-chaining": "warn",
      "no-unused-expressions": "warn",
      "no-unused-labels": "warn",
      "no-unused-private-class-members": "warn",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-underscore-dangle": ["warn", { allow: ["_tag"] }],
      "no-useless-backreference": "warn",
      "no-useless-catch": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-with": "warn",
      "require-yield": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
      "oxc/bad-array-method-on-arguments": "warn",
      "oxc/bad-char-at-comparison": "warn",
      "oxc/bad-comparison-sequence": "warn",
      "oxc/bad-min-max-func": "warn",
      "oxc/bad-object-literal-comparison": "warn",
      "oxc/bad-replace-all-arg": "warn",
      "oxc/const-comparisons": "warn",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/missing-throw": "warn",
      "oxc/number-arg-out-of-range": "warn",
      "oxc/only-used-in-recursion": "warn",
      "oxc/uninvoked-array-callback": "warn",
      "typescript/await-thenable": "warn",
      "typescript/no-array-delete": "warn",
      "typescript/no-base-to-string": "warn",
      "typescript/no-duplicate-enum-values": "warn",
      "typescript/no-duplicate-type-constituents": "warn",
      "typescript/no-extra-non-null-assertion": "warn",
      "typescript/no-floating-promises": "error",
      "typescript/no-for-in-array": "warn",
      "typescript/no-implied-eval": "warn",
      "typescript/no-meaningless-void-operator": "warn",
      "typescript/no-misused-new": "warn",
      "typescript/no-non-null-asserted-optional-chain": "warn",
      "typescript/no-redundant-type-constituents": "warn",
      "typescript/no-this-alias": "warn",
      "typescript/no-unnecessary-parameter-property-assignment": "warn",
      "typescript/no-unsafe-declaration-merging": "warn",
      "typescript/no-unsafe-unary-minus": "warn",
      "typescript/no-unsafe-type-assertion": "off",
      "typescript/no-useless-empty-export": "warn",
      "typescript/no-wrapper-object-types": "warn",
      "typescript/prefer-as-const": "warn",
      "typescript/require-array-sort-compare": "warn",
      "typescript/restrict-template-expressions": "warn",
      "typescript/triple-slash-reference": "warn",
      "typescript/consistent-type-definitions": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/unbound-method": "warn",
      "unicorn/no-await-in-promise-methods": "warn",
      "unicorn/no-empty-file": "warn",
      "unicorn/no-invalid-fetch-options": "warn",
      "unicorn/no-invalid-remove-event-listener": "warn",
      "unicorn/no-new-array": "warn",
      "unicorn/no-single-promise-in-promise-methods": "warn",
      "unicorn/no-thenable": "warn",
      "unicorn/no-unnecessary-await": "warn",
      "unicorn/no-useless-fallback-in-spread": "warn",
      "unicorn/no-useless-length-check": "warn",
      "unicorn/no-useless-spread": "warn",
      "unicorn/prefer-set-size": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "max-lines": ["error", { max: 250, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": [
        "error",
        { max: 150, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      complexity: ["error", { max: 15 }],
    },
    overrides: [
      {
        // D01-B: packages/* must not touch a runtime; adapters/* may.
        files: ["packages/*/src/**"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              patterns: [
                {
                  group: ["bun:*", "node:*", "@cloudflare/*", "react-native", "react-native/*"],
                  message:
                    "packages/* are runtime-neutral (D01-B). Put this behind a port in adapters/*.",
                },
              ],
            },
          ],
          "no-restricted-globals": [
            "error",
            { name: "Bun", message: "runtime-neutral (D01-B)" },
            { name: "process", message: "runtime-neutral (D01-B)" },
            { name: "window", message: "runtime-neutral (D01-B)" },
            { name: "document", message: "runtime-neutral (D01-B)" },
          ],
        },
      },
      {
        files: [
          "**/*.test.ts",
          "**/*.spec.ts",
          "**/*.bench.ts",
          "**/__tests__/**",
          "**/tests/**",
          "**/*.setup.ts",
          "**/test-setup.ts",
        ],
        rules: {
          "no-restricted-imports": "off",
          "no-restricted-globals": "off",
          "max-lines": "off",
          "max-lines-per-function": "off",
          complexity: "off",
          "no-console": "off",
          "node/no-process-env": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-unsafe-return": "off",
        },
      },
      {
        files: ["**/*.config.ts", "**/*.config.js", "**/*.config.mjs", "**/*.config.mts"],
        rules: { "node/no-process-env": "off", "max-lines": "off" },
      },
      {
        files: ["scripts/**", "tooling/**", "bench/**"],
        env: { node: true },
        rules: {
          "max-lines": "off",
          "max-lines-per-function": "off",
          complexity: "off",
          "no-console": "off",
          "node/no-process-env": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-unsafe-return": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-argument": "off",
        },
      },
    ],
  },

  fmt: {
    ignorePatterns: [
      "**/dist/**",
      "research/**",
      "plan/**",
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".windsurf/**",
      "tools/oxlint/anti-slop/**",
    ],
    sortPackageJson: { sortScripts: true },
    sortImports: {
      groups: [
        "type-import",
        ["value-builtin", "value-external"],
        "type-internal",
        "value-internal",
        ["type-parent", "type-sibling", "type-index"],
        ["value-parent", "value-sibling", "value-index"],
        "unknown",
      ],
    },
  },
});
