/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ShellRouteRouteImport } from "./routes/_shell/route";
import { Route as ShellIndexRouteImport } from "./routes/_shell/index";
import { Route as ShellIssuesIdRouteImport } from "./routes/_shell/issues/$id";

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShellRouteRoute,
} as any);
const ShellIssuesIdRoute = ShellIssuesIdRouteImport.update({
  id: "/issues/$id",
  path: "/issues/$id",
  getParentRoute: () => ShellRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof ShellIndexRoute;
  "/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof ShellIndexRoute;
  "/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof ShellRouteRouteWithChildren;
  "/_shell/": typeof ShellIndexRoute;
  "/_shell/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/issues/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/issues/$id";
  id: "__root__" | "/_shell" | "/_shell/" | "/_shell/issues/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ShellRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ShellIndexRouteImport;
      parentRoute: typeof ShellRouteRoute;
    };
    "/_shell/issues/$id": {
      id: "/_shell/issues/$id";
      path: "/issues/$id";
      fullPath: "/issues/$id";
      preLoaderRoute: typeof ShellIssuesIdRouteImport;
      parentRoute: typeof ShellRouteRoute;
    };
  }
}

interface ShellRouteRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute;
  ShellIssuesIdRoute: typeof ShellIssuesIdRoute;
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellIssuesIdRoute: ShellIssuesIdRoute,
};

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
