/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ShellRouteRouteImport } from "./routes/_shell/route";
import { Route as IdentityRouteImport } from "./routes/identity";
import { Route as PeopleRouteImport } from "./routes/people";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ShellIndexRouteImport } from "./routes/_shell/index";
import { Route as ShellIssuesIdRouteImport } from "./routes/_shell/issues/$id";

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const IdentityRoute = IdentityRouteImport.update({
  id: "/identity",
  path: "/identity",
  getParentRoute: () => rootRouteImport,
} as any);
const PeopleRoute = PeopleRouteImport.update({
  id: "/people",
  path: "/people",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShellRouteRoute,
} as any);
const ShellIssuesIdRoute = ShellIssuesIdRouteImport.update({
  id: "/issues/$id",
  path: "/issues/$id",
  getParentRoute: () => ShellRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof ShellIndexRoute;
  "/identity": typeof IdentityRoute;
  "/people": typeof PeopleRoute;
  "/settings": typeof SettingsRoute;
  "/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRoutesByTo {
  "/identity": typeof IdentityRoute;
  "/people": typeof PeopleRoute;
  "/settings": typeof SettingsRoute;
  "/": typeof ShellIndexRoute;
  "/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof ShellRouteRouteWithChildren;
  "/identity": typeof IdentityRoute;
  "/people": typeof PeopleRoute;
  "/settings": typeof SettingsRoute;
  "/_shell/": typeof ShellIndexRoute;
  "/_shell/issues/$id": typeof ShellIssuesIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/identity" | "/people" | "/settings" | "/issues/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/identity" | "/people" | "/settings" | "/" | "/issues/$id";
  id:
    | "__root__"
    | "/_shell"
    | "/identity"
    | "/people"
    | "/settings"
    | "/_shell/"
    | "/_shell/issues/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren;
  IdentityRoute: typeof IdentityRoute;
  PeopleRoute: typeof PeopleRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ShellRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/identity": {
      id: "/identity";
      path: "/identity";
      fullPath: "/identity";
      preLoaderRoute: typeof IdentityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/people": {
      id: "/people";
      path: "/people";
      fullPath: "/people";
      preLoaderRoute: typeof PeopleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ShellIndexRouteImport;
      parentRoute: typeof ShellRouteRoute;
    };
    "/_shell/issues/$id": {
      id: "/_shell/issues/$id";
      path: "/issues/$id";
      fullPath: "/issues/$id";
      preLoaderRoute: typeof ShellIssuesIdRouteImport;
      parentRoute: typeof ShellRouteRoute;
    };
  }
}

interface ShellRouteRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute;
  ShellIssuesIdRoute: typeof ShellIssuesIdRoute;
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellIssuesIdRoute: ShellIssuesIdRoute,
};

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
  IdentityRoute: IdentityRoute,
  PeopleRoute: PeopleRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
