import type { ByteStream } from "./framing.js";

/**
 * Whether a link is still there, on a medium that will not say (RFC-0005, book ch. 16).
 *
 * **A socket does not always learn that its network went away.** Switch a phone's Wi-Fi off and
 * the connection underneath is not closed so much as abandoned: no close event, no write that
 * throws, no status callback. The transport above goes on holding what it believes is a live
 * link, and a write made in that state is folded locally, handed to a link that carries nothing,
 * and sits there. The same failure arrives over peer-to-peer Wi-Fi when the radio is switched
 * off, and over a relay when the network moves — where it cost a user ~37 seconds of a screen
 * that would not update, which is where {@link SILENCE_FACTOR} comes from.
 *
 * So the only thing that can notice is a deadline, and a deadline needs something to expect. The
 * relay has one already: its server sends keepalives, and a client that hears none for 2.5 of
 * them hangs up. Two peers have no server between them, so each end prods a link that has gone
 * quiet and the far side's answer is what the near side's deadline is re-armed on — the same
 * shape, with the keepalive generated by whoever noticed the silence first.
 *
 * A busy link is never prodded, because frames arriving *are* the evidence. What is paid on an
 * idle mesh is one exchange per link per keepalive, and what it buys is that a link which died
 * without saying so is closed and re-dialled rather than held for ever.
 */

/**
 * How often a link that has gone quiet is prodded. Well under the relay's 15s, because these
 * media can re-dial in a round trip: what a longer interval saves is a frame, and what it costs
 * is the seconds a person spends looking at a screen that will not update.
 */
export const DEFAULT_KEEPALIVE_MS = 5_000;

/**
 * Silence worth this many keepalives is a dead link.
 *
 * The relay's figure, for the relay's reason: one lost prod must not end a working link, and two
 * in a row on a medium that delivers in order is not a glitch. Below 2 a single slow round trip
 * hangs up on a peer that is answering; far above it is the ~37-second window this exists to
 * close.
 */
export const SILENCE_FACTOR = 2.5;

export interface LivenessOptions<K> {
  /** How often a quiet link is prodded; the deadline is {@link SILENCE_FACTOR} times this. */
  readonly everyMs?: number;
  /**
   * Prod the links, because at least one of them has gone quiet.
   *
   * Aimed at the medium rather than at one link, because that is the handle an adapter has: a
   * transport can re-request on every session it holds and cannot reach inside one of them. A
   * prod on a link that was never quiet costs a frame and is the price of not threading a bridge
   * back out to the adapter that opened it.
   */
  readonly probe: () => void;
  /**
   * This link has been silent past the deadline. Nothing reported it and nothing will: close it,
   * and forget the peer, so the medium's next sighting is a fresh one rather than one discovery
   * has already seen.
   */
  readonly dead: (link: K) => void;
  readonly now?: () => number;
}

export interface Liveness<K> {
  /**
   * Watch a link, and hand back the stream to pass on. Wrapping rather than subscribing, because
   * an adapter that could watch a link without reading it is an adapter that will one day watch
   * one it never hears from and hang up on a peer that is answering.
   */
  readonly watch: (link: K, stream: ByteStream) => ByteStream;
  /** A frame arrived on a link this unit does not own the stream of — a medium that framed for us. */
  readonly heard: (link: K) => void;
  /** This link has ended, by this unit's verdict or anybody else's. */
  readonly forget: (link: K) => void;
  /** No links, no timer: what `close` leaves behind. */
  readonly stop: () => void;
}

/** See the module doc: a deadline per link, re-armed by anything arriving on it. */
export function createLiveness<K>(options: LivenessOptions<K>): Liveness<K> {
  const everyMs = options.everyMs ?? DEFAULT_KEEPALIVE_MS;
  const now = options.now ?? (() => Date.now());
  const deadlineMs = everyMs * SILENCE_FACTOR;
  const lastHeard = new Map<K, number>();
  let beat: ReturnType<typeof setInterval> | undefined;

  const stop = (): void => {
    clearInterval(beat);
    beat = undefined;
  };

  const check = (): void => {
    const at = now();
    let quiet = false;
    // deleted from under the iterator, which a Map allows and which is what `dead` does here
    for (const [link, heardAt] of lastHeard) {
      const silence = at - heardAt;
      if (silence > deadlineMs) {
        // forgotten before the verdict is given: `dead` closes the link, which forgets it again,
        // and a second pass over a link already being closed is a second close
        lastHeard.delete(link);
        options.dead(link);
        continue;
      }
      if (silence >= everyMs) quiet = true;
    }
    if (lastHeard.size === 0) stop();
    // once, however many links are quiet: the prod goes to the medium, not to one of them
    if (quiet) options.probe();
  };

  const heard = (link: K): void => {
    lastHeard.set(link, now());
    if (beat !== undefined) return;
    beat = setInterval(check, everyMs);
    // a deadline is not a reason for a process to stay alive
    beat.unref?.();
  };

  return {
    heard,
    watch: (link, stream) => {
      heard(link);
      return {
        ...stream,
        onData: (cb) =>
          stream.onData((bytes) => {
            heard(link);
            cb(bytes);
          }),
      };
    },
    forget: (link) => {
      lastHeard.delete(link);
      if (lastHeard.size === 0) stop();
    },
    stop: () => {
      lastHeard.clear();
      stop();
    },
  };
}
